name: Document workflow

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: 16

      - run: yarn install

      - name: Build @system
        working-directory: ./packages/system
        run: "yarn run build"

      - name: Build @icons
        working-directory: ./packages/icons
        run: "yarn run build"

      - name: Build @ui
        working-directory: ./packages/ui
        run: "yarn run build"

      - run: yarn run test:ci

      - name: Build docs
        working-directory: ./packages/web
        run: "yarn run build"

      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.DEV_NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=packages/web/public --prod
          secrets: '["DEV_NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
